### ISSUE TITLE
Téléversement sur Chromebook

### ISSUE THREAD

**Issue by JulienAramino** [technologiescollege/BlocklyArduino_electrified#2]
Bonjour,

Je n'arrive pas à avoir la fonctionnalité téléverser sur le Chromebook de mon fils ni sous mon Windows.
J'ai installé le plugins Codebender sur les deux.

En utilisant codebender.cc cela fonctionne sur le Chromebook et Windows. La carte est reconnue et le port aussi.
(/dev/ttyACMO,  Arduino Mega 2560)

J'ai installé BlocklyArduino_electrified sur un serveur Apache sur mon réseau local sous Ubuntu.
Mais je ne peux pas choisir le port et le téléversement est bloqué (dans code)

J'ai parallèlement essayé ArduinoDroid, mais celui ci ne trouve pas la carte.

Je ne comprend pas d'où pourrais venir le problème (sachant que cela marche avec le site codebender.cc).
Pourriez vous m'indiquer la marche à suivre pour faire fonctionner sur un Chromebook le téléversement ?

Merci
Cordialement

**Comment by SebCanet** [comment]
Bonjour,
ce paquet logiciel Blockly@rduino + compilateur n'est compatible qu'avec Windows hélas. J'ai rompu la compatibilité avec Codebender il y a des années de ça car le développement s'était arrêté, ils sont revenus avec un modèle payant, et toutes les cartes ne sont pas incluses. Sans compter qu'il faille sans cesse courir derrière les mises à jour des navigateurs et de ce plugin que je ne maîtrise pas. Rien que sur leur site : "Firefox support is discontinued. Please use Google Chrome or Chromium."

Que cela ne fonctionne pas sous Windows est étrange par contre...quel message d'erreur avez vous ?

Quant à l'install sur serveur elle ne peut pas fonctionner car il faut un client local pour récupérer le code et le téléverser dans la carte, on ne m'a jamais demandé un tel développement.

Le plus simple est d'installer l'IDE Arduino, comme pour une installation Linux (des détails là: [https://www.stevencombs.com/arduino/2020/01/20/arduino-on-chromeos.html](https://www.stevencombs.com/arduino/2020/01/20/arduino-on-chromeos.html)), et de copier coller le code de Blockly@rduino dedans.

Pour d'autres détails, il y a le forum: [http://blockly.technologiescollege.fr/forum/](http://blockly.technologiescollege.fr/forum/)

Je clos le ticket car j'ai bien trop de travail à développer pour me lancer hélas dans Chrome OS, désolé.

**Comment by JulienAramino** [comment]
Ok merci pour votre réponse rapide.
En fait j'ai activé family link sur le Chromebook pour contrôler le temps sur l'écran, et donc je ne peux utiliser linux dessus.
J'ai peur qu'il faille attendre qu'ils développent Arduino IDE pour Chromebook. (Ou que j'enlève le contrôle parental)
Pour Windows je n'ai pas vu d'erreur juste la selectbox du port est grisé et les boutons autours me montre un signe interdit rouge au survol. (Avec chrome).

**Comment by SebCanet** [comment]
Quand ces options apparaissent grisées, c'est parce que Blockly@rduino est lancé dans un navigateur, et non pas dans l'environnement BlocklyArduino_electrified (car embarqué par Electron).
Pour résoudre les pb sous Windows (et sous Chrome avez vous essayé le lien pour installer l'IDE Arduino dessus ?), merci de poster avec des captures d'écran sur le forum.

**Comment by JulienAramino** [comment]
En effet l'objectif était de l'utiliser via le navigateur à partir d'une installation sur le réseau local. Je n'ai pas essayé avec l'IDE. Comme cela n'est pas possible je ne vais pas investiguer plus faute de temps. 
En tout cas merci et je salue votre travail.

**Comment by SebCanet** [comment]
Il y a des pistes:
- soit via le navigateur + IDE en local pour compiler vers la carte en local,
- soit mettre sur un serveur le compilateur ([https://github.com/RMeurisse/ArduinoBuilder](https://github.com/RMeurisse/ArduinoBuilder)) et faire une modif de Blockly@rduino (et me la soumettre pour remettre au collectif :-D )
Mais je n'ai hélas pas le temps pour investiguer car j'ai d'autres projets à faire avancer.

**Comment by JulienAramino** [comment]
Merci pour ce lien vers le compilateur.
A l'occasion j'essayerai.

**Comment by JulienAramino** [comment]
Pourriez vous m'aider à comprendre comment  puis-je envoyer le program compilé à la carte via USB en javascript ? (Sans codebender justement)

**Comment by SebCanet** [comment]
Hélas, comme je vous disais je n'ai pas le temps de me pencher sur le développement de ce projet, qui est pourtant hyper intéressant. Actuellement je travaille sur un reboot total de BlocklyDuino en v2 ([https://github.com/BlocklyDuino](https://github.com/BlocklyDuino)) afin d'y intégrer toutes les dernières modifications de Blockly (accessibilité, typage, etc), ainsi que sur HackCable ([https://github.com/A-S-T-U-C-E/HackCable](https://github.com/A-S-T-U-C-E/HackCable)).

Désolé de ne pouvoir vous aider, il faut regarder les méthodes employées dans Blockly4Arduino ([https://github.com/ingegno/Blockly4Arduino](https://github.com/ingegno/Blockly4Arduino)).

**Comment by JulienAramino** [comment]
Merci,
J'ai trouvé ceci:
https://github.com/noopkat/avrgirl-arduino
Je pense que ça fait le boulot en conjonction avec ArduinoBuilder.
Je pense faire une interface sur laquelle serait copier coller le code de BlockyArduino

**Comment by SebCanet** [comment]
Excellent projet ! C'est vrai qu'interfacer les deux serait un super projet, ArduinoBuilder compile puison récupère et on téléverse via avrgirl-arduino.
Ce pourquoi j'ai arrêté les développements autour de Codebender (à part leurs pb, l'arrêt de développement, etc) c'est aussi car les normes ne cessent de changer, et qu'on ne sait jamais ce que sera la nouvelle version des navigateurs, ce qu'ils bloquent ou acceptent, etc. Pas facile à suivre...

**Comment by JulienAramino** [comment]
Bonjour,

Du coup j'ai fait ceci:
https://gitlab.com/aramino.julien/ArduinoPusher
https://gitlab.com/aramino.julien/ArduinoBuilder (serveur RMeurisse)

Cela marche bien.
L'astuce: il faut HTTPS, PWA et il faut souscrire a https://developer.chrome.com/origintrials/ pour l’accès au serial port sur le chromebook de mon fils (sans accès au chrome/flags), en attendant que cette fonctionnalité soit disponible au grand public.

Merci

**Comment by SebCanet** [comment]
Excellente nouvelle ! Merci beaucoup des efforts et du partage !
Je tâcherai de tester, et voir comment créer un système autonome, un exécutable multiplateforme qui s'affranchirait de nodejs une fois compilé.

**Comment by JulienAramino** [comment]
Avec Nuxtjs justement on peut générer une app static ;-) (npm run generate)

**Comment by SebCanet** [comment]
Pour les release Windows, je passe par Electron.

Je pense intégrer ce travail (un jour) dans BlocklyDuino2 ([https://github.com/BlocklyDuino/BlocklyDuino-v2/issues/18](https://github.com/BlocklyDuino/BlocklyDuino-v2/issues/18)).
Peux tu rajouter une doc ou une vidéo pour l'installation/utilisation ? Ça peut intéresser des profs.

**Comment by JulienAramino** [comment]
Une vidéo non j'aurais pas le temps, je peux détailler l'installation, mais bon ça reste compliqué pour le SSL (je ne sais pas si un nom de domaine est obligatoire ou juste une adresse IP suffit avec openSSL)

**Comment by SebCanet** [comment]
Je pensais juste à une capture d'écran pour expliquer globalement le principe, rien de compliqué, un truc rapide.
